#!/usr/bin/env bash
# 生成 .env 需要的高熵 secrets (PECKER_SIGNATURE_SECRET / PECKER_JWT_SECRET).
#
# 用法:
#   bash scripts/gen-secrets.sh              # 打印到 stdout,手动复制
#   bash scripts/gen-secrets.sh >> .env      # 追加到 .env
#   bash scripts/gen-secrets.sh --check .env # 校验现有 .env 里的 secret 强度(不生成)

set -euo pipefail

# 选 openssl 或 python 生成 32 字节 hex (64 字符,远超 api/main.py 要求的 32)
_gen() {
  if command -v openssl >/dev/null 2>&1; then
    openssl rand -hex 32
  elif command -v python >/dev/null 2>&1; then
    python -c "import secrets; print(secrets.token_hex(32))"
  elif command -v python3 >/dev/null 2>&1; then
    python3 -c "import secrets; print(secrets.token_hex(32))"
  else
    echo "ERROR: 需要 openssl 或 python(3) 生成随机串" >&2
    exit 1
  fi
}

# 校验模式: 不生成,只报告 .env 里 secret 长度
if [[ "${1:-}" == "--check" ]]; then
  env_file="${2:-.env}"
  if [[ ! -f "$env_file" ]]; then
    echo "ERROR: $env_file 不存在" >&2
    exit 1
  fi
  ok=true
  for key in PECKER_SIGNATURE_SECRET PECKER_JWT_SECRET; do
    line=$(grep -E "^${key}=" "$env_file" || true)
    val="${line#${key}=}"
    val="${val%\"}"; val="${val#\"}"
    if [[ -z "$val" ]]; then
      echo "✗ $key 未设置"
      ok=false
    elif [[ "${#val}" -lt 32 ]]; then
      echo "⚠ $key 长度 ${#val} < 32, 生产环境建议重新生成"
      ok=false
    else
      echo "✓ $key 长度 ${#val} OK"
    fi
  done
  $ok || exit 1
  exit 0
fi

# 默认模式: 生成新 secrets
echo "# Auto-generated by scripts/gen-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "PECKER_SIGNATURE_SECRET=$(_gen)"
echo "PECKER_JWT_SECRET=$(_gen)"
echo "# 如需写入 .env: bash scripts/gen-secrets.sh >> .env"
